### ISSUE TITLE
bug: sales_report schema validation errors `begin_date` and `end_date`

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-appstore#2]
This `jsonschema.exceptions.ValidationError: '01/31/2023' is not a 'date'`

- [begin_date](https://github.com/MeltanoLabs/tap-appstore/blob/4b0648e2fcae51502d537b922ee82756c86f53ab/tap_appstore/schemas/sales_report.json#L87C10-L87C20)
- end_date

@cjohnhanson @edgarrmondragon this seems to not be the case when I run with target-jsonl but it fails with target-postgres. Would you expect '01/31/2023' to be a valid string date according to json schema? I didnt expect it to be valid.

**Comment by edgarrmondragon** [comment]
I don't think '01/31/2023' is a valid `date` string.

It seems target-jsonl depends on an eight year old (!!) version of `python-jsonschema`, but the `date` format was only added in JSON Schema Draft 7, so target-jsonl is probably just missing the `date` format check.

**Comment by pnadolny13** [comment]
@edgarrmondragon Wow thats old! I saw someone recently built a new target-jsonl on the SDK https://github.com/cmhh/target-jsonl.

I'll do a more thorough testing of the streams and fix any other schema issues I find along with this one.

**Comment by pnadolny13** [comment]
`subscriber_report.purchase_date` is throwing `jsonschema.exceptions.ValidationError: '' is not a 'date'`

**Comment by edgarrmondragon** [comment]
would it be a bad idea to update the schema to remove the `"format": "date"` from problematic fields? the alternative is probably to implement the equivalent of the SDK's `post_process`.

**Comment by pnadolny13** [comment]
@edgarrmondragon yeah thats my plan. I dont really want to reformat the data in this tap. Maybe if we make and SDK version though.

**Comment by pnadolny13** [comment]
I resolved all of these that I could test in the `key_file_str` branch https://github.com/Automattic/tap-appstore/pull/5.
